### ISSUE TITLE
Question regarding peak timestamp

### ISSUE THREAD

**Issue by ZhelunChen** [HichamJohra/energy_flexibility_kpis#14]
@kingsleynweye

https://github.com/HichamJohra/energy_flexibility_kpis/blob/7995b08755e0db39ec580c6b625d8af341f8a6af/energy_flexibility_kpis/kpi.py#L19

Should it be a single occurance of timestamp or multiple (i.e., a period of time)? To me, peak is a period of time.

**Comment by kingsleynweye** [comment]
Yeah, I'm not too sure @ZhelunChen. The definition int the [Google Sheet](https://docs.google.com/spreadsheets/d/1tSN3PIu-lh9aSiU775-RULTRy2o2owIzV-iwymNXszo/edit#gid=118080661) is that it is a single value. Also, the assumption is that the profiles provided by the user are for a single evaluation period so within an evaluation period there will be one timestamp where the peak occurs.

**Comment by HichamJohra** [comment]
@ZhelunChen , I agree with @kingsleynweye

**Comment by ZhelunChen** [comment]
@kingsleynweye @hicham-johra OK, I see where this is coming from. According to the definition, this would be a specific hour that the grid is at its peak. If so, two follow up questions would be:

1. If the data provided by the user has internal smaller than an hour, say minute by minute, what would be the peak demand? The demand of a specific timestamp, or the average of an hour?
2. I am aware there exists company that bill peak demand based on the highest 30 minutes electricity consumption in a month, what should be the peak demand in such scenario?

**Comment by HichamJohra** [comment]
@ZhelunChen , to me, peak power demand is "instantaneous" because it's in W, i.e., J/sec so it's equivalent to an amount of energy use divided by an infinitely small period of time. So of course in practice it is always an average power over an certain integration time, but I would consider it stricto sensus as an intantaneous power value for a single given time stamp, no matter the sampling rate of the time series

**Comment by ZhelunChen** [comment]
@HichamJohra Yes. I am totally agree with you. 

As a user, if I only know that a specifc hour is the peak hour, and I have data with much smaller sampling rate than one hour, what should I use as the peak timestamp input to this KPI function. Should I preprocess my data first in order to use this KPI? How should I preprocess it? ... Or maybe this KPI is just not for me, and I should use energy ralted ones instead.

These are just some thoughts that I want to share. I am fine with the way it is right now.

**Comment by HichamJohra** [comment]
Yes, resampling support/utility function will be integrated into the package to prepare the data to the sampling requirements of certain KPIs, so that, indeed, if people want the hourly peak power reduction (which thus corresponds to the peak hourly average power) then data has to be pre-down-sampled-mean to hourly time series.

**Comment by ZhelunChen** [comment]
@kingsleynweye @HichamJohra  That makes sense. Thank you guys!
